services:
  - type: web
    name: skillsync-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn skillsynch_backend.wsgi:application --bind 0.0.0.0:$PORT
    plan: free
